apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1
  labels:
    app: app-1
  namespace: default
spec:
  selector:
    matchLabels:
      app: app-1
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
        - name: app-1
          image: app-1:0.0.1
          ports:
            - containerPort: 3000