apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: app-1
  labels:
    app: app-1
spec:
  type: ClusterIP
  selector:
    app: app-1
  ports:
    - protocol: TCP
      name: http
      port: 3000
      targetPort: 3000