apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-1
  namespace: default
spec:
  interval: 15m
  path: "./k8s"
  prune: true
  sourceRef:
    kind: GitRepository
    name: app-1